import express from "express";
import cartRoutes from "./cart.routes.js";
import categoryRoutes from "./category.routes.js";
import subCategoryRoutes from "./subCategory.routes.js";
import subSubCategoryRoutes from "./subSubCategory.routes.js";
import subSubSubCategoryRoutes from "./subSubSubCategory.routes.js";
import serviceRoutes from "./service.routes.js";
import slugRoutes from "./slug.routes.js";
import timeSlotRoutes from "./timeSlot.routes.js";
import homeRoutes from "./home.routes.js";
import paymentRoutes from "./payment.routes.js";
import blogRoutes from "./blog.routes.js";
import blogCategoryRoutes from "./blogCategory.routes.js";
import termsConditionsRoutes from "./termsConditions.routes.js";
import privacyPolicyRoutes from "./privacyPolicy.routes.js";
import refundRoutes from "./refundPolicy.routes.js";
import impactRoutes from "./impact.routes.js";
import contactEnquiryRoutes from "./contactEnquiry.routes.js";
import jobPostingRoutes from "./jobPosting.routes.js";
import jobApplicationRoutes from "./jobApplication.routes.js";
import rateCardRoutes from "./rateCard.routes.js";
import reviewRoutes from "./review.routes.js";
import disclaimerRoutes from "./disclaimer.routes.js";
import metaTagRoutes from "./metaTag.route.js";
import appRoutes from "./app.route.js";

const router = express.Router();

router.use("/category", categoryRoutes);
router.use("/sub-category", subCategoryRoutes);
router.use("/sub-sub-category", subSubCategoryRoutes);
router.use("/sub-sub-sub-category", subSubSubCategoryRoutes);
router.use("/service", serviceRoutes);
router.use("/cart", cartRoutes);
router.use("/slug", slugRoutes);
router.use("/time-slot", timeSlotRoutes);
router.use("/home", homeRoutes);
router.use("/payment", paymentRoutes);
router.use("/blog-category", blogCategoryRoutes);
router.use("/blog", blogRoutes);
router.use("/terms-conditions", termsConditionsRoutes);
router.use("/privacy-policy", privacyPolicyRoutes);
router.use("/refund-policy", refundRoutes);
router.use("/impact", impactRoutes);
router.use("/contact-enquiry", contactEnquiryRoutes);
router.use("/job-posting", jobPostingRoutes);
router.use("/job-application", jobApplicationRoutes);
router.use("/rate-card", rateCardRoutes);
router.use("/review", reviewRoutes);
router.use("/disclaimer", disclaimerRoutes);
router.use("/meta-tag", metaTagRoutes);
router.use("/app", appRoutes);

export default router;