import express from "express";
import addressRoutes from "./address.routes.js";
import cartRoutes from "./cart.routes.js";
import authRoutes from "./auth.routes.js";
import userRoutes from "./user.routes.js";
import categoryRoutes from "./category.routes.js";
import subCategoryRoutes from "./subCategory.routes.js";
import subSubCategoryRoutes from "./subSubCategory.routes.js";
import subSubSubCategoryRoutes from "./subSubSubCategory.routes.js";
import serviceRoutes from "./service.routes.js";
import slugRoutes from "./slug.routes.js";
import timeSlotRoutes from "./timeSlot.routes.js";
import bookingRoutes from "./booking.routes.js";
import reviewRoutes from "./review.routes.js";
import kycRoutes from "./kyc.routes.js";
import profileRoutes from "./servicemanProfile.routes.js";
import trainingScheduleRoutes from "./trainingSchedule.routes.js";
import trainingScheduleSubmitRoutes from "./trainingScheduleSubmit.routes.js";
import earningRoutes from "./earning.routes.js";
import servicemanBookingRoutes from "./servicemanBooking.routes.js";
import transactionRoutes from "./transaction.routes.js";
import homePageBannerRoutes from "./homePageBanner.routes.js";
import homePageSeviceRoutes from "./homePageService.routes.js";
import homePageSliderRoutes from "./homePageSlider.routes.js";
import brandLogoRoutes from "./brandLogo.routes.js";
import expertTechnicianRoutes from "./expertTechnician.routes.js";
import giPromiseRoutes from "./giPromise.routes.js";
import requirementFromCustomerRoutes from "./requirementFromCustomer.routes.js";
import serviceIncludedRoutes from "./serviceIncluded.routes.js";
import whyChooseUsRoutes from "./whyChooseUs.routes.js";
import serviceFaqRoutes from "./serviceFaq.routes.js";
import blogRoutes from "./blog.routes.js";
import blogCategoryRoutes from "./blogCategory.routes.js";
import termsConditionsRoutes from "./termsConditions.routes.js";
import privacyPolicyRoutes from "./privacyPolicy.routes.js";
import refundPolicyRoutes from "./refundPolicy.routes.js";
import impactRoutes from "./impact.routes.js";
import contactEnquiryRoutes from "./contactEnquiry.routes.js";
import jobPostingRoutes from "./jobPosting.routes.js";
import jobApplicationRoutes from "./jobApplication.routes.js";
import rateCardRoutes from "./rateCard.routes.js";
import brandRoutes from "./brand.route.js";
import cityRoutes from "./city.routes.js";
import insuranceRoutes from "./insurance.routes.js";
import productStoreRoutes from "./productStore.routes.js";
import providerCertificateRoutes from "./providerCertificate.routes.js";
import supportTicketRoutes from "./supportTicket.routes.js";
import trainingRoutes from "./training.routes.js";
import trainingAttendanceRoutes from "./trainingAttendance.routes.js";
import walletRoutes from "./wallet.routes.js";
import localityRoutes from "./locality.routes.js";
import areaZoneRoutes from "./areaZone.routes.js";
import disclaimerRoutes from "./discliamer.routes.js";
import metaTagRoutes from "./metaTag.route.js";
import dashboardRoutes from "./dashboard.route.js";
import zoneRoutes from "./zone.route.js";
import servicemanEarningRoutes from "./servicemanEarning.routes.js";
import supportContentRoutes from "./support.routes.js";
import appRoutes from "./app.route.js";
import servicemanByZone from "./servicemanByZone.routes.js";
import pincodeRoutes from "./pincode.routes.js";
import cashCollectedRoutes from "./cashCollctedLogger.route.js";
import invoiceRoutes from "./invoice.routes.js";
import roleRoutes from "./role.route.js";
import subAdminRoutes from "./subadmin.routes.js";
import notificationRoutes from "./notification.route.js";
import bandTransferRoutes from "./bankTransfer.routes.js";
import bookingAdditionalPartRoutes from "./bookingAdditionalPart.routes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/category", categoryRoutes);
router.use("/sub-category", subCategoryRoutes);
router.use("/sub-sub-category", subSubCategoryRoutes);
router.use("/sub-sub-sub-category", subSubSubCategoryRoutes);
router.use("/service", serviceRoutes);
router.use("/cart", cartRoutes);
router.use("/address", addressRoutes);
router.use("/slug", slugRoutes);
router.use("/time-slot", timeSlotRoutes);
router.use("/booking", bookingRoutes);
router.use("/review", reviewRoutes);
router.use("/kyc", kycRoutes);
router.use("/serviceman-profile", profileRoutes);
router.use("/serviceman-byzone", servicemanByZone);
router.use("/training-schedule", trainingScheduleRoutes);
router.use("/training-schedule-submit", trainingScheduleSubmitRoutes);
router.use("/earning", earningRoutes);
router.use("/serviceman-booking", servicemanBookingRoutes);
router.use("/transaction", transactionRoutes);
router.use("/home-page-banner", homePageBannerRoutes);
router.use("/home-page-service", homePageSeviceRoutes);
router.use("/home-page-slider", homePageSliderRoutes);
router.use("/brand-logo", brandLogoRoutes);
router.use("/expert-technician", expertTechnicianRoutes);
router.use("/gi-promise", giPromiseRoutes);
router.use("/requirement-from-customer", requirementFromCustomerRoutes);
router.use("/service-included", serviceIncludedRoutes);
router.use("/why-choose-us", whyChooseUsRoutes);
router.use("/service-faq", serviceFaqRoutes);
router.use("/blog-category", blogCategoryRoutes);
router.use("/blog", blogRoutes);
router.use("/terms-conditions", termsConditionsRoutes);
router.use("/privacy-policy", privacyPolicyRoutes);
router.use("/refund-policy", refundPolicyRoutes);
router.use("/disclaimer", disclaimerRoutes);
router.use("/impact", impactRoutes);
router.use("/contact-enquiry", contactEnquiryRoutes);
router.use("/job-posting", jobPostingRoutes);
router.use("/job-application", jobApplicationRoutes);
router.use("/rate-card", rateCardRoutes);
router.use("/brand", brandRoutes);
router.use("/city", cityRoutes);
router.use("/insurance", insuranceRoutes);
router.use("/product-store", productStoreRoutes);
router.use("/provider-certificate", providerCertificateRoutes);
router.use("/support-ticket", supportTicketRoutes);
router.use("/training", trainingRoutes);
router.use("/training-attendance", trainingAttendanceRoutes);
router.use("/wallet", walletRoutes);
router.use("/locality", localityRoutes);
router.use("/area-zone", areaZoneRoutes);
router.use("/meta-tag", metaTagRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/zone", zoneRoutes);
router.use("/serviceman-earning", servicemanEarningRoutes);
router.use("/support-content", supportContentRoutes);
router.use("/app", appRoutes);
router.use("/pincode", pincodeRoutes);
router.use("/cash-collected", cashCollectedRoutes);
router.use("/invoice", invoiceRoutes);
router.use("/role", roleRoutes);
router.use("/sub-admin", subAdminRoutes);
router.use("/notification", notificationRoutes);
router.use("/bank-transfer", bandTransferRoutes);
router.use("/booking-additional-part", bookingAdditionalPartRoutes);

export default router;