import express from "express";
import addressRoutes from "./address.routes.js";
import cartRoutes from "./cart.routes.js";
import authRoutes from "./auth.routes.js";
import userRoutes from "./user.routes.js";
import categoryRoutes from "./category.routes.js";
import subCategoryRoutes from "./subCategory.routes.js";
import subSubCategoryRoutes from "./subSubCategory.routes.js";
import subSubSubCategoryRoutes from "./subSubSubCategory.routes.js";
import serviceRoutes from "./service.routes.js";
import slugRoutes from "./slug.routes.js";
import timeSlotRoutes from "./timeSlot.routes.js";
import bookingRoutes from "./booking.routes.js";
import reviewRoutes from "./review.routes.js";
import kycRoutes from "./kyc.routes.js";
import profileRoutes from "./servicemanProfile.routes.js";
import trainingScheduleRoutes from "./trainingSchedule.routes.js";
import earningRoutes from "./earning.routes.js";
import servicemanBookingRoutes from "./servicemanBooking.routes.js";
import transactionRoutes from "./transaction.routes.js";
import homePageBannerRoutes from "./homePageBanner.routes.js";
import homePageSeviceRoutes from "./homePageService.routes.js";
import homePageSliderRoutes from "./homePageSlider.routes.js";
import brandLogoRoutes from "./brandLogo.routes.js";
import expertTechnicianRoutes from "./expertTechnician.routes.js";
import giPromiseRoutes from "./giPromise.routes.js";
import requirementFromCustomerRoutes from "./requirementFromCustomer.routes.js";
import serviceIncludedRoutes from "./serviceIncluded.routes.js";
import whyChooseUsRoutes from "./whyChooseUs.routes.js";
import serviceFaqRoutes from "./serviceFaq.routes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/category", categoryRoutes);
router.use("/sub-category", subCategoryRoutes);
router.use("/sub-sub-category", subSubCategoryRoutes);
router.use("/sub-sub-sub-category", subSubSubCategoryRoutes);
router.use("/service", serviceRoutes);
router.use("/cart", cartRoutes);
router.use("/address", addressRoutes);
router.use("/slug", slugRoutes);
router.use("/time-slot", timeSlotRoutes);
router.use("/booking", bookingRoutes);
router.use("/review", reviewRoutes);
router.use("/kyc", kycRoutes);
router.use("/serviceman-profile", profileRoutes);
router.use("/training-schedule", trainingScheduleRoutes);
router.use("/earning", earningRoutes);
router.use("/serviceman-booking", servicemanBookingRoutes);
router.use("/transaction", transactionRoutes);
router.use("/home-page-banner", homePageBannerRoutes);
router.use("/home-page-service", homePageSeviceRoutes);
router.use("/home-page-slider", homePageSliderRoutes);
router.use("/brand-logo", brandLogoRoutes);
router.use("/expert-technician", expertTechnicianRoutes);
router.use("/gi-promise", giPromiseRoutes);
router.use("/requirement-from-customer", requirementFromCustomerRoutes);
router.use("/service-included", serviceIncludedRoutes);
router.use("/why-choose-us", whyChooseUsRoutes);
router.use("/service-faq", serviceFaqRoutes);

export default router;